# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='fromuser',
            new_name='fromuser_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='touser',
            new_name='touser_id',
        ),
    ]
