# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_auto_20170409_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='fromuser_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='touser_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='fromuser',
            field=models.ForeignKey(db_column='fromuser', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='touser',
            field=models.ForeignKey(db_column='touser', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='touser', to=settings.AUTH_USER_MODEL),
        ),
    ]
