# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20170409_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
